GET http://localhost:4000/products

###

GET http://localhost:4000/users/1

###

GET http://localhost:4000/users/2/carts?_sort=productId

###

POST http://localhost:4000/carts
Content-Type: application/json

{
    "userId": 2,
    "productId": 2,
    "quantity": 2
}

###

GET http://localhost:4000/api/hello

###

POST  http://localhost:4000/api/users/signup
Content-Type: application/json

{
    "name": "Jo",
    "email": "test@mail.com",
    "password": "test12345"
}

###

POST  http://localhost:4000/api/users/login
Content-Type: application/json

{
    "email": "test@mail.com",
    "password": "test12345"
}

###

POST http://localhost:4000/api/products
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1OTgwODIyMywiZXhwIjoxNjU5ODExODIzfQ.FZ3FVUckVJFQhgqEWcAz8fy_Dm8V_ujb2_b8NjPQFTs
Content-Type: application/json

{
    "name": "Iphone 14",
    "price": 800
}